development:
  adapter: postgresql
  encoding: unicode
  database: app-dev
  pool: 5
  timeout: 5000
  username: csigi
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: app-dev
  pool: 5
  timeout: 5000
  username: csigi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: app-dev
  pool: 5
  timeout: 5000
  username: csigi
  password:

cucumber:
  <<: *test